name: Artifacts
on:
    workflow_dispatch:
jobs:
    artifacts:
        runs-on: ubuntu-latest
        steps:
            - name: echo
              run: echo "yo what up"
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm ci
            - name: Build Project
              run: npm run build
            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                name: test-dist
                path: dist