name: Outputs
on: workflow_dispatch
jobs:
    create-output:
        runs-on: ubuntu-latest
        outputs:
            context: ${{steps.ctx.outputs.context}}
        steps:
            - name: GH Context
              id: ctx
              run: echo "context=${{toJson(github.event.workflow)}}" >> $GITHUB_OUTPUT
    display-output:
        needs: create-output
        runs-on: ubuntu-latest
        steps:
            - name: Echo
              run: echo "${{needs.create-output.outputs.context}}"
